### ISSUE TITLE
returned secret merge behaviour

### ISSUE THREAD

**Issue by RosscoeP** [petems/petems-hiera_vault#38] opened 2019-06-19 10:47 UTC
my hiera includes:-
      mounts:
        sandpit:
          - function/%{function}
          - job/%{job}
          - climate/%{climate}
          - product/%{product}
          - role/%{role}
          - stack/%{stack}
          - platform/%{platform}
          - common
I do not want 'merge: first' which appears to be the behaviour of hiera_vault at present.
I have modified my copy of hiera_vault.rb (version 0.3.0) to now accept 
options:
  <merge: (first|unique|hash|deep)>
assuming first if not present.

**Comment by petems** [comment] 2019-06-23 13:43
I'm not sure the question here, could you explain? 

I think a fix I recently merged to allow multiple hierachical lookups, could you try with version 0.4.1 and see if this works for you #29

**Comment by traviscosgrave** [comment] 2019-08-20 17:27
If you try the version in my PR is uses the hiera feature to define uris to lookup which means it supports all of the merge behaviour you would expect from the yaml or json backend.

**Comment by petems** [comment] 2020-05-17 09:06
I'm closing this for now due to lack of updates from OP, if you can give me a reproducible use case of the issue, happy to re-open and investigate 👍

**Closed by petems** 2020-05-17 09:06 UTC
